//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductTracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductTrackerEntities : DbContext
    {
        public ProductTrackerEntities()
            : base("name=ProductTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mtAttribute> mtAttribute { get; set; }
        public DbSet<product> product { get; set; }
        public DbSet<productType> productType { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<productAttribute> productAttribute { get; set; }
        public DbSet<productTree> productTree { get; set; }
    }
}
