//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class productType
    {
        public productType()
        {
            this.product = new HashSet<product>();
        }
    
        public int typeID { get; set; }
        public string typeName { get; set; }
        public int rootType { get; set; }
    
        public virtual ICollection<product> product { get; set; }
    }
}
