//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class productAttribute
    {
        public int productID { get; set; }
        public int attributeID { get; set; }
        public string value { get; set; }
    
        public virtual mtAttribute mtAttribute { get; set; }
        public virtual product product { get; set; }
    }
}
