//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.productAttribute = new HashSet<productAttribute>();
        }
    
        public int id { get; set; }
        public int typeID { get; set; }
        public string name { get; set; }
    
        public virtual productType productType { get; set; }
        public virtual ICollection<productAttribute> productAttribute { get; set; }
        public virtual productTree productTree { get; set; }
    }
}
