//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProductTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _default {
            get {
                object obj = ResourceManager.GetObject("_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addButton {
            get {
                object obj = ResourceManager.GetObject("addButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый тип объекта успешно добавлен..
        /// </summary>
        internal static string AddProdType_Add_succes {
            get {
                return ResourceManager.GetString("AddProdType_Add_succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано имя объекта.
        /// </summary>
        internal static string AdministrationWindows_createNewButton_Click_Не_указано_имя_объекта {
            get {
                return ResourceManager.GetString("AdministrationWindows_createNewButton_Click_Не_указано_имя_объекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой элемент уже создан в структуре..
        /// </summary>
        internal static string AdministrationWindows_createNewButton_Click_Такой_элемент_уже_создан_в_структуре_ {
            get {
                return ResourceManager.GetString("AdministrationWindows_createNewButton_Click_Такой_элемент_уже_создан_в_структуре_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип элемента не выбран.
        /// </summary>
        internal static string AdministrationWindows_createNewButton_Click_Тип_элемента_не_выбран {
            get {
                return ResourceManager.GetString("AdministrationWindows_createNewButton_Click_Тип_элемента_не_выбран", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для удаления изделия воспользуйтесь меню Журнал изделий.
        /// </summary>
        internal static string AdministrationWindows_deleteButton_Click_Для_удаления_изделия_воспользуйтесь_меню_Журнал_изделий {
            get {
                return ResourceManager.GetString("AdministrationWindows_deleteButton_Click_Для_удаления_изделия_воспользуйтесь_меню" +
                        "_Журнал_изделий", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сначала удалите дочерние элементы объекта.
        /// </summary>
        internal static string AdministrationWindows_deleteButton_Click_Сначала_удалите_дочерние_элементы_объекта {
            get {
                return ResourceManager.GetString("AdministrationWindows_deleteButton_Click_Сначала_удалите_дочерние_элементы_объект" +
                        "а", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в состав объекта: .
        /// </summary>
        internal static string AdministrationWindows_specTree_AfterSelect_Добавить_в_состав_объекта {
            get {
                return ResourceManager.GetString("AdministrationWindows_specTree_AfterSelect_Добавить_в_состав_объекта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание нового элемента конструкции.
        /// </summary>
        internal static string AdministrationWindows_Создание_нового_элемента_конструкции {
            get {
                return ResourceManager.GetString("AdministrationWindows_Создание_нового_элемента_конструкции", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо ввести логин и пароль пользователя..
        /// </summary>
        internal static string afButLog_login_emptyData {
            get {
                return ResourceManager.GetString("afButLog_login_emptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных.
        /// </summary>
        internal static string afButLog_login_emptyData_MessageCaption {
            get {
                return ResourceManager.GetString("afButLog_login_emptyData_MessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо ввести логин пользователя..
        /// </summary>
        internal static string afButLog_login_emptyLogin {
            get {
                return ResourceManager.GetString("afButLog_login_emptyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо ввести пароль пользователя..
        /// </summary>
        internal static string afButLog_login_emptyPsw {
            get {
                return ResourceManager.GetString("afButLog_login_emptyPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь: .
        /// </summary>
        internal static string AutorisationForm_Пользователь {
            get {
                return ResourceManager.GetString("AutorisationForm_Пользователь", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атрибуты объектов.
        /// </summary>
        internal static string Configurator_Атрибуты_объектов {
            get {
                return ResourceManager.GetString("Configurator_Атрибуты_объектов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект успешно переименован..
        /// </summary>
        internal static string configurator_Объекто_успешно_переименован {
            get {
                return ResourceManager.GetString("configurator_Объекто_успешно_переименован", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы объектов.
        /// </summary>
        internal static string Configurator_Типы_объектов {
            get {
                return ResourceManager.GetString("Configurator_Типы_объектов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный атрибут уже существует..
        /// </summary>
        internal static string Configurator_Указанный_атрибут_уже_существует {
            get {
                return ResourceManager.GetString("Configurator_Указанный_атрибут_уже_существует", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный тип уже существует..
        /// </summary>
        internal static string Configurator_Указанный_тип_уже_существует {
            get {
                return ResourceManager.GetString("Configurator_Указанный_тип_уже_существует", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атрибуты объектов.
        /// </summary>
        internal static string confTree_Root_nood0 {
            get {
                return ResourceManager.GetString("confTree_Root_nood0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dellButton {
            get {
                object obj = ResourceManager.GetObject("dellButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap detail {
            get {
                object obj = ResourceManager.GetObject("detail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция не выполнена.
        /// </summary>
        internal static string error_operation_msg {
            get {
                return ResourceManager.GetString("error_operation_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введен неверный Логин пользователя..
        /// </summary>
        internal static string notFoundLogin {
            get {
                return ResourceManager.GetString("notFoundLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изделие.
        /// </summary>
        internal static string productType_Изделие {
            get {
                return ResourceManager.GetString("productType_Изделие", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sborka {
            get {
                object obj = ResourceManager.GetObject("sborka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция выполнена.
        /// </summary>
        internal static string successful_operation_msg {
            get {
                return ResourceManager.GetString("successful_operation_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap technology {
            get {
                object obj = ResourceManager.GetObject("technology", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введная пара логин/пароль неверна..
        /// </summary>
        internal static string User_Autorisation_Логин_и_пароль_неверны {
            get {
                return ResourceManager.GetString("User_Autorisation_Логин_и_пароль_неверны", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь успешно добавлен..
        /// </summary>
        internal static string user_created {
            get {
                return ResourceManager.GetString("user_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой пользователь уже сущесвтует..
        /// </summary>
        internal static string user_there_in_db {
            get {
                return ResourceManager.GetString("user_there_in_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uzel {
            get {
                object obj = ResourceManager.GetObject("uzel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изделия.
        /// </summary>
        internal static string Изделия {
            get {
                return ResourceManager.GetString("Изделия", resourceCulture);
            }
        }
    }
}
