//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class productTree
    {
        public int productID { get; set; }
        public Nullable<int> parentID { get; set; }
        public Nullable<int> inWork { get; set; }
        public string activeWorker { get; set; }
    
        public virtual product product { get; set; }
    }
}
