CREATE TABLE UserRole(
roleId INT PRIMARY KEY IDENTITY NOT NULL,
[name] VARCHAR(100) NOT NULL
)
 

CREATE TABLE Users(
userID INT PRIMARY KEY IDENTITY NOT NULL,
[login] VARCHAR(100) NOT NULL,
psw VARCHAR(100) NOT NULL,
fio VARCHAR(150) NULL,
roleId INT FOREIGN KEY REFERENCES UserRole (roleId) NOT NULL
)
